//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fhs.Cachless.C_DataAccess_Log.DBModel
{
    using System;
    using System.Collections.Generic;
    
    using Fhs.Cachless.D_Common.Model.BaseModels;
    public partial class AppRequestLogTable:_BaseDbModel //ClassName //Head Of Class
    {
    	protected override string GetChildClassName(){return "AppRequestLogTable";}
        
        public Nullable<int> Fk_DeviceId { get; set; } //Property
        public Nullable<int> Fk_TokenId { get; set; } //Property
        public string AppUserInfo { get; set; } //Property
        public string UrlAddress { get; set; } //Property
        public int StatusCode { get; set; } //Property
        public string StatusCodeStr { get; set; } //Property
        public int AnswerCode { get; set; } //Property
        public string AnswerStr { get; set; } //Property
        public System.DateTime RequestDate { get; set; } //Property
        public double ResponseTime { get; set; } //Property
        public string MessageList { get; set; } //Property
        public string MainToken { get; set; } //Property
        public string Ip { get; set; } //Property
        public string ResponseMessage { get; set; } //Property
        public string ApplicationOwner { get; set; } //Property
        
        
        public string RequestHeader { get; set; } //Property
    }
}
