//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fhs.Cachless.C_DataAccess_Log.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Fhs_CachLessDBEntities_Log : DbContext
    {
        public Fhs_CachLessDBEntities_Log()
            : base("name=Fhs_CachLessDBEntities_Log")
        {
        }
    
    public Fhs_CachLessDBEntities_Log(string connection)
            : base(connection)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppRequestLogTable> AppRequestLogTables { get; set; }
    }
}
